export interface ContentModerationPolicy {
  blockedDomains: readonly string[];
  blockedTextTerms: readonly string[];
  blockedUrlTerms: readonly string[];
}

export const contentModerationPolicy: ContentModerationPolicy = {
  blockedDomains: [
    "beeg.com",
    "bongacams.com",
    "brazzers.com",
    "cam4.com",
    "chaturbate.com",
    "eporner.com",
    "fansly.com",
    "fapello.com",
    "hanime.tv",
    "hqporner.com",
    "livejasmin.com",
    "manyvids.com",
    "motherless.com",
    "nhentai.net",
    "nuvid.com",
    "onlyfans.com",
    "porn.com",
    "pornhub.com",
    "redtube.com",
    "rule34.xxx",
    "spankbang.com",
    "stripchat.com",
    "thumbzilla.com",
    "tnaflix.com",
    "tube8.com",
    "txxx.com",
    "xhamster.com",
    "xhamsterlive.com",
    "xnxx.com",
    "xvideos.com",
    "youjizz.com",
    "youporn.com",
  ],
  blockedTextTerms: ["porn", "pornography", "xxx", "nsfw", "hentai", "rule34", "onlyfans"],
  blockedUrlTerms: [
    "porn",
    "xxx",
    "xvideos",
    "pornhub",
    "xhamster",
    "redtube",
    "xnxx",
    "youporn",
    "hentai",
    "rule34",
    "nhentai",
    "hanime",
    "brazzers",
    "onlyfans",
    "chaturbate",
    "livejasmin",
    "stripchat",
    "cam4",
    "bongacams",
  ],
};
