import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("agent registry keeps the default row compact and reveals management on demand", () => {
  const source = readFileSync(new URL("./AgentRegistryPanel.tsx", import.meta.url), "utf8");
  const form = readFileSync(new URL("./AgentVersionForm.tsx", import.meta.url), "utf8");
  assert.match(source, />Manage</);
  assert.match(source, /Change version/);
  assert.match(source, /Review behavior/);
  assert.match(source, /Autonomous requests/);
  assert.match(source, /aria-controls="agent-review-behavior"/);
  assert.match(source, /aria-controls="agent-autonomous-requests"/);
  assert.match(source, /Technical details/);
  assert.match(source, /Audit history/);
  assert.match(source, /Only workspace owners and admins can make changes/);
  assert.match(source, /agentRevision = 0/);
  assert.match(source, /onAgentsChanged\?\.\(\)/);
  assert.match(form, /Declared provider/);
  assert.match(form, /Saving creates an immutable version/);
  assert.match(source, /const \[showArchived, setShowArchived\] = useState\(false\)/);
  assert.match(source, /showArchived \? agents : agents\.filter\(agent => agent\.status === "active"\)/);
  assert.match(source, /Show archived \(\$\{archivedAgentCount\}\)/);
  assert.match(source, /Hide archived/);
  assert.match(source, /aria-pressed=\{showArchived\}/);
  assert.match(source, /visibleAgents\.map/);
  assert.doesNotMatch(source, /Agent registry/);
  assert.doesNotMatch(source, /Durable identities and declared model versions/);
  assert.doesNotMatch(source, /No approved agents are registered/);
  assert.doesNotMatch(source, /No active agents are registered/);
  assert.doesNotMatch(source, /Register agent|Register a durable agent|createAgent/);
  assert.doesNotMatch(source, /method: "POST"[\s\S]{0,200}\/agents/);
  assert.doesNotMatch(source, /verified model|model accuracy|truth score/i);
});
