import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("agent registry keeps the default row compact and reveals management on demand", () => {
  const source = readFileSync(new URL("./AgentRegistryPanel.tsx", import.meta.url), "utf8");
  const form = readFileSync(new URL("./AgentVersionForm.tsx", import.meta.url), "utf8");
  assert.match(source, />Manage</);
  assert.match(source, /Change workflow version/);
  assert.match(source, /Review behavior/);
  assert.match(source, /Autonomous requests/);
  assert.match(source, /aria-controls="agent-review-behavior"/);
  assert.match(source, /aria-controls="agent-autonomous-requests"/);
  assert.match(source, /Technical details/);
  assert.match(source, /Audit history/);
  assert.match(source, /Only workspace owners and admins can make changes/);
  assert.match(source, /agentRevision = 0/);
  assert.match(source, /onAgentsChanged\?\.\(\)/);
  assert.match(form, /Workflow name/);
  assert.match(form, /provider: "unknown"/);
  assert.match(form, /model: "unknown"/);
  assert.match(form, /Saving creates an immutable workflow version/);
  assert.doesNotMatch(form, />\s*Declared provider/);
  assert.doesNotMatch(form, />\s*Declared model/);
  assert.doesNotMatch(form, />\s*Model version/);
  assert.match(source, /const \[showArchived, setShowArchived\] = useState\(false\)/);
  assert.match(source, /showArchived \? agents : agents\.filter\(agent => agent\.status === "active"\)/);
  assert.match(source, /Show archived \(\$\{archivedAgentCount\}\)/);
  assert.match(source, /Hide archived/);
  assert.match(source, /aria-pressed=\{showArchived\}/);
  assert.match(source, /visibleAgents\.map/);
  assert.match(source, /Human assurance/);
  assert.match(source, /Review configuration/);
  assert.match(source, /Frequency/);
  assert.match(source, /Reviewers/);
  assert.match(source, /Response window/);
  assert.match(source, /Base payment/);
  assert.match(source, /Agent authority/);
  assert.match(source, /Every eligible output/);
  assert.match(source, /Adaptive ·/);
  assert.match(source, /Invited reviewers · private workspace material/);
  assert.match(source, /RateLoop network · public-safe material/);
  assert.match(source, /USDC \/ reviewer/);
  assert.match(source, /Policy checks ready/);
  assert.match(source, /Owner-approved requests ready/);
  assert.match(source, /Automatic requests ready/);
  assert.match(source, /Blocked · finish review setup/);
  assert.match(source, /Blocked · reconnect the agent/);
  assert.match(source, /Blocked · automatic requests are off/);
  assert.doesNotMatch(source, /Feedback Bonus|feedback bonus/);
  assert.match(source, /Baseline review coverage/);
  assert.match(source, /Agent-human agreement/);
  assert.match(source, /95% lower bound/);
  assert.match(source, /Evidence stays separate by execution profile, workflow version, policy, workflow, risk tier/);
  assert.match(source, /does not create a global score/);
  assert.match(source, /Execution model unavailable/);
  assert.match(source, /Requested \{scope\.executionProfile\.primary\.requestedModel\}/);
  assert.match(source, /reasoningEffort/);
  assert.match(source, /serviceTier/);
  assert.match(source, /Multi-model/);
  assert.match(source, /Execution details/);
  assert.match(source, /Execution metadata is reported by the connected host/);
  assert.match(source, /Observed runs/);
  assert.match(source, /Average duration/);
  assert.match(source, /Average input tokens/);
  assert.match(source, /Average output tokens/);
  assert.match(source, /Average reasoning tokens/);
  assert.match(source, /Models in this profile/);
  assert.match(source, /Workflow v\{agent\.currentVersion\.versionNumber\}/);
  assert.doesNotMatch(source, /\{agent\.currentVersion\.declaredModel\}/);
  assert.doesNotMatch(source, />Declared provider</);
  assert.match(source, /first evidence scope starts with 100% review/);
  assert.doesNotMatch(source, /trust score|accuracy score/i);
  assert.doesNotMatch(source, /Agent registry/);
  assert.doesNotMatch(source, /Durable identities and declared model versions/);
  assert.doesNotMatch(source, /No approved agents are registered/);
  assert.doesNotMatch(source, /No active agents are registered/);
  assert.doesNotMatch(source, /Register agent|Register a durable agent|createAgent/);
  assert.doesNotMatch(source, /method: "POST"[\s\S]{0,200}\/agents/);
  assert.doesNotMatch(source, /verified model|model accuracy|truth score/i);
});
