import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("agent details and review information render in task-focused views", () => {
  const source = readFileSync(new URL("./AgentRegistryPanel.tsx", import.meta.url), "utf8");
  const form = readFileSync(new URL("./AgentVersionForm.tsx", import.meta.url), "utf8");
  assert.match(source, /view === "connection"/);
  assert.match(source, /view === "reviews"/);
  assert.match(source, /Change workflow version/);
  assert.match(source, /Edit reviews/);
  assert.match(source, /configuration_required" \? "Finish setup" : "Edit reviews"/);
  assert.match(source, /aria-controls="agent-human-review-editor"/);
  assert.match(source, /activeReviewAgentId === agent\.agentId/);
  assert.match(source, /onReviewAgentChange/);
  assert.doesNotMatch(source, />Review behavior</);
  assert.doesNotMatch(source, />Autonomous requests</);
  assert.match(source, /Technical details/);
  assert.match(source, /Audit history/);
  assert.match(source, /agentRevision = 0/);
  assert.match(source, /onAgentsChanged\?\.\(\)/);
  assert.match(form, /Workflow name/);
  assert.match(form, /provider: "unknown"/);
  assert.match(form, /model: "unknown"/);
  assert.match(form, /Saving creates an immutable workflow version/);
  assert.doesNotMatch(form, />\s*Declared provider/);
  assert.doesNotMatch(form, />\s*Declared model/);
  assert.doesNotMatch(form, />\s*Model version/);
  assert.doesNotMatch(form, /Deployment name/i);
  assert.doesNotMatch(source, /declaredDeploymentName|>Deployment</i);
  assert.match(source, /const \[showArchived, setShowArchived\] = useState\(false\)/);
  assert.match(source, /showArchived \? agents : agents\.filter\(agent => agent\.status === "active"\)/);
  assert.match(source, /Show archived \(\$\{archivedAgentCount\}\)/);
  assert.match(source, /Hide archived/);
  assert.match(source, /aria-pressed=\{showArchived\}/);
  assert.match(source, /visibleAgents\.map/);
  assert.match(source, /Review configuration/);
  assert.match(source, /Frequency/);
  assert.match(source, /Reviewers/);
  assert.match(source, /Question author/);
  assert.match(source, /One owner-set question/);
  assert.match(source, /Agent writes each review question · feedback only/);
  assert.match(source, /Response window/);
  assert.match(source, /Base payment/);
  assert.match(source, /Feedback Bonus/);
  assert.match(source, /Agent authority/);
  assert.match(source, /Every eligible output/);
  assert.match(source, /Manual handoff only/);
  assert.match(source, /Manual handoffs only/);
  assert.match(source, /configuration\.selection\.mode !== "manual"/);
  assert.match(source, /Adaptive ·/);
  assert.match(source, /Invited reviewers · private workspace material/);
  assert.match(source, /RateLoop network · public-safe material/);
  assert.match(source, /USDC \/ reviewer/);
  assert.match(source, /Policy checks ready/);
  assert.match(source, /Owner-approved requests ready/);
  assert.match(source, /Automatic requests ready/);
  assert.match(source, /Blocked · finish review setup/);
  assert.match(source, /Blocked · reconnect the agent/);
  assert.match(source, /Blocked · automatic requests are off/);
  assert.match(source, /Workflow v\{agent\.currentVersion\.versionNumber\}/);
  assert.doesNotMatch(source, /\{agent\.currentVersion\.declaredModel\}/);
  assert.doesNotMatch(source, />Declared provider</);
  assert.doesNotMatch(source, /Human assurance|No eligible output has reached RateLoop yet|global score/i);
  assert.doesNotMatch(source, /trust score|accuracy score/i);
  assert.doesNotMatch(source, /Agent registry/);
  assert.doesNotMatch(source, /Durable identities and declared model versions/);
  assert.doesNotMatch(source, /No approved agents are registered/);
  assert.doesNotMatch(source, /No active agents are registered/);
  assert.doesNotMatch(source, /Register agent|Register a durable agent|createAgent/);
  assert.doesNotMatch(source, /method: "POST"[\s\S]{0,200}\/agents/);
  assert.doesNotMatch(source, /verified model|model accuracy|truth score/i);
});

test("agent management actions stay visible while technical records remain optional", () => {
  const source = readFileSync(new URL("./AgentRegistryPanel.tsx", import.meta.url), "utf8");
  assert.match(source, />\s*Change workflow version\s*</);
  assert.match(source, />\s*Deactivate\s*</);
  assert.doesNotMatch(source, /<summary[^>]*>Manage<\/summary>/);
  assert.match(source, /<summary[^>]*>\s*Technical details/);
  assert.match(source, /Audit history \(\{agent\.versions\.length\}\)/);
});

test("the agent evidence card shows only labeled host-reported and observed metadata", () => {
  const source = readFileSync(new URL("./AgentRegistryPanel.tsx", import.meta.url), "utf8");
  assert.match(source, /Model and evidence/);
  assert.match(source, /Declared model/);
  assert.match(source, /Coverage stage/);
  assert.match(source, /Observed workflows/);
  assert.match(source, /Observed risk tiers/);
  assert.match(source, /Evaluation profile/);
  assert.match(source, /reported by the connected host, not independently verified/);
  assert.doesNotMatch(source, /Capabilities and limits/);
  assert.doesNotMatch(source, /Intended purpose/);
  assert.doesNotMatch(source, /Known limitations/);
  assert.doesNotMatch(source, /Do-not-use conditions/);
  assert.doesNotMatch(source, /capability-statement/);
});

test("the connection card labels the connection lane as host-reported and defaults to the weakest claim", () => {
  const source = readFileSync(new URL("./AgentRegistryPanel.tsx", import.meta.url), "utf8");
  assert.match(source, /Connected via RateLoop plugin · host-reported/);
  assert.match(source, /Advisory MCP connection — plugin hooks not reported/);
  assert.match(source, /Device-flow connection — plugin hooks not reported/);
  assert.match(source, /view === "connection" && agent\.reportedConnectionLane/);
  assert.doesNotMatch(source, /verified plugin|plugin verified/i);
});
