import {
  readdirSync,
  statSync,
  readFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "fs";
import { join, dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */`;

const RAW_DEPLOYMENT_CONTRACTS_TO_SKIP = new Set([
  "ERC1967Proxy",
  "TransparentUpgradeableProxy",
]);

const REQUIRED_NON_LOCAL_DEPLOYMENT_EXPORT_CONTRACTS = [
  "TimelockController",
  "CuryoGovernor",
  "MeshReputation",
  "FrontendRegistry",
  "ProfileRegistry",
  "ContentRegistry",
  "RoundVotingEngine",
  "ProtocolConfig",
  "RoundRewardDistributor",
  "QuestionRewardPoolEscrow",
  "X402QuestionSubmitter",
  "FeedbackBonusEscrow",
  "CategoryRegistry",
  "RaterRegistry",
  "RaterDeclarationRegistry",
  "VoterIdNFT",
  "ParticipationPool",
];

function getDirectories(path) {
  if (!existsSync(path)) {
    return [];
  }

  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isDirectory();
  });
}

function getFiles(path) {
  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isFile();
  });
}

function parseTransactionAndReceiptRun(filePath) {
  try {
    const content = readFileSync(filePath, "utf8");
    const broadcastData = JSON.parse(content);
    return {
      transactions: broadcastData.transactions || [],
      receipts: broadcastData.receipts || [],
    };
  } catch (error) {
    console.warn(`Warning: Could not parse ${filePath}:`, error.message);
    return [];
  }
}

function getDeploymentHistory(broadcastPath) {
  const files = getFiles(broadcastPath);
  const deploymentHistory = new Map();

  // Sort files to process them in chronological order
  const runFiles = files
    .filter(
      (file) =>
        file.startsWith("run-") &&
        file.endsWith(".json") &&
        !file.includes("run-latest")
    )
    .sort((a, b) => {
      // Extract run numbers and compare them
      const runA = parseInt(a.match(/run-(\d+)/)?.[1] || "0");
      const runB = parseInt(b.match(/run-(\d+)/)?.[1] || "0");
      return runA - runB;
    });

  for (const file of runFiles) {
    const { transactions, receipts } = parseTransactionAndReceiptRun(
      join(broadcastPath, file)
    );

    for (const tx of transactions) {
      if (tx.transactionType === "CREATE" || tx.transactionType === "CREATE2") {
        // Store or update contract deployment info
        deploymentHistory.set(tx.contractAddress, {
          contractName: tx.contractName,
          address: tx.contractAddress,
          deploymentFile: file,
          transaction: tx,
          receipt: receipts.find((r) => r.transactionHash === tx.hash),
        });
      }
    }
  }

  return Array.from(deploymentHistory.values());
}

function getArtifactOfContract(contractName) {
  const current_path_to_artifacts = join(
    __dirname,
    "..",
    `out/${contractName}.sol`
  );

  if (!existsSync(current_path_to_artifacts)) return null;

  const artifactJson = JSON.parse(
    readFileSync(`${current_path_to_artifacts}/${contractName}.json`)
  );

  return artifactJson;
}

function getInheritedFromContracts(artifact) {
  let inheritedFromContracts = [];
  if (artifact?.ast) {
    for (const astNode of artifact.ast.nodes) {
      if (astNode.nodeType == "ContractDefinition") {
        if (astNode.baseContracts.length > 0) {
          inheritedFromContracts = astNode.baseContracts.map(
            ({ baseName }) => baseName.name
          );
        }
      }
    }
  }
  return inheritedFromContracts;
}

function getInheritedFunctions(mainArtifact) {
  const inheritedFromContracts = getInheritedFromContracts(mainArtifact);
  const inheritedFunctions = {};
  for (const inheritanceContractName of inheritedFromContracts) {
    const artifact = getArtifactOfContract(inheritanceContractName);
    if (artifact) {
      const {
        abi,
        ast: { absolutePath },
      } = artifact;
      for (const abiEntry of abi) {
        if (abiEntry.type == "function") {
          inheritedFunctions[abiEntry.name] = absolutePath;
        }
      }
    }
  }
  return inheritedFunctions;
}

function processAllDeployments(broadcastPath) {
  const scriptFolders = getDirectories(broadcastPath);
  const allDeployments = new Map();
  const allDeploymentsByAddress = new Map();
  const latestBroadcastBlockNumbers = {};
  const latestBroadcastDeploymentAddresses = {};
  const latestBroadcastTimestamps = {};

  scriptFolders.forEach((scriptFolder) => {
    const scriptPath = join(broadcastPath, scriptFolder);
    const chainFolders = getDirectories(scriptPath);

    chainFolders.forEach((chainId) => {
      const chainPath = join(scriptPath, chainId);
      const deploymentHistory = getDeploymentHistory(chainPath);

      deploymentHistory.forEach((deployment) => {
        const deployedOnBlock =
          deployment?.receipt?.blockNumber &&
          Number(BigInt(deployment.receipt.blockNumber));
        if (deployedOnBlock) {
          latestBroadcastBlockNumbers[chainId] = Math.max(
            latestBroadcastBlockNumbers[chainId] || 0,
            deployedOnBlock
          );
        }
        const timestamp = parseInt(
          deployment.deploymentFile.match(/run-(\d+)/)?.[1] || "0"
        );
        if (timestamp > (latestBroadcastTimestamps[chainId] || 0)) {
          latestBroadcastTimestamps[chainId] = timestamp;
          latestBroadcastDeploymentAddresses[chainId] = new Set();
        }
        if (timestamp === latestBroadcastTimestamps[chainId]) {
          latestBroadcastDeploymentAddresses[chainId].add(
            deployment.address.toLowerCase()
          );
        }
        const key = `${chainId}-${deployment.contractName}`;
        const addressKey = `${chainId}-${deployment.address.toLowerCase()}`;

        // Only update if this deployment is newer
        if (
          !allDeployments.has(key) ||
          timestamp > allDeployments.get(key).timestamp
        ) {
          allDeployments.set(key, {
            ...deployment,
            timestamp,
            chainId,
            deploymentScript: scriptFolder,
            deployedOnBlock,
          });
        }

        if (
          !allDeploymentsByAddress.has(addressKey) ||
          timestamp > allDeploymentsByAddress.get(addressKey).timestamp
        ) {
          allDeploymentsByAddress.set(addressKey, {
            ...deployment,
            timestamp,
            chainId,
            deploymentScript: scriptFolder,
            deployedOnBlock,
          });
        }
      });
    });
  });

  const allContracts = {};
  const deployers = {};

  allDeployments.forEach((deployment) => {
    const { chainId, contractName } = deployment;
    if (RAW_DEPLOYMENT_CONTRACTS_TO_SKIP.has(contractName)) return;

    // Capture deployer address from first CREATE transaction per chain
    if (!deployers[chainId]) {
      const from = deployment.transaction?.transaction?.from;
      if (from) deployers[chainId] = from;
    }

    const artifact = getArtifactOfContract(contractName);

    if (artifact) {
      if (!allContracts[chainId]) {
        allContracts[chainId] = {};
      }

      allContracts[chainId][contractName] = {
        address: deployment.address,
        abi: artifact.abi,
        inheritedFunctions: getInheritedFunctions(artifact),
        deploymentFile: deployment.deploymentFile,
        deploymentScript: deployment.deploymentScript,
        deployedOnBlock:
          deployment?.deployedOnBlock &&
          Number(BigInt(deployment.deployedOnBlock)),
      };
    }
  });

  return {
    contracts: allContracts,
    deployers,
    deploymentsByAddress: allDeploymentsByAddress,
    latestBroadcastBlockNumbers,
    latestBroadcastDeploymentAddresses,
  };
}

function readExistingDeployedContracts(targetFile) {
  if (!existsSync(targetFile)) return {};

  const content = readFileSync(targetFile, "utf8");
  const match = content.match(
    /const deployedContracts(?::[^=]+)?=\s*({[\s\S]*?});\s*export default deployedContracts;/
  );
  if (!match) return {};

  try {
    return Function(`"use strict"; return (${match[1]});`)();
  } catch (error) {
    console.warn(
      `Warning: Could not preserve existing deployed contracts from ${targetFile}:`,
      error.message
    );
    return {};
  }
}

function deploymentExportContractNames(chainDeployments) {
  if (typeof chainDeployments !== "object" || chainDeployments === null) {
    return new Set();
  }
  return new Set(
    Object.entries(chainDeployments)
      .filter(([address]) => address.startsWith("0x"))
      .map(([, contractName]) => contractName)
  );
}

function deploymentExportRequiredAddresses(chainDeployments) {
  if (typeof chainDeployments !== "object" || chainDeployments === null) {
    return [];
  }

  const requiredContractNames = new Set(
    REQUIRED_NON_LOCAL_DEPLOYMENT_EXPORT_CONTRACTS
  );
  return Object.entries(chainDeployments)
    .filter(
      ([address, contractName]) =>
        address.startsWith("0x") && requiredContractNames.has(contractName)
    )
    .map(([address]) => address.toLowerCase());
}

function isCompleteDeploymentExport(chainDeployments) {
  return (
    typeof chainDeployments === "object" &&
    chainDeployments !== null &&
    chainDeployments.deploymentComplete === "true"
  );
}

function deploymentExportBlockNumber(chainDeployments) {
  if (typeof chainDeployments !== "object" || chainDeployments === null) {
    return 0;
  }
  const blockNumber = chainDeployments.deploymentBlockNumber;
  if (blockNumber === undefined || blockNumber === null || blockNumber === "") {
    return 0;
  }
  return Number(BigInt(blockNumber));
}

function hasGeneratedContracts(generatedContracts) {
  return (
    typeof generatedContracts === "object" &&
    generatedContracts !== null &&
    Object.keys(generatedContracts).length > 0
  );
}

function isNonLocalDeploymentChain(chainId) {
  const numericChainId = Number(chainId);
  return (
    numericChainId !== DEPLOY_TARGET_TO_CHAIN_ID.localhost &&
    Object.values(DEPLOY_TARGET_TO_CHAIN_ID).includes(numericChainId)
  );
}

function assertCompleteNonLocalDeploymentExport(
  chainDeployments,
  latestBroadcastBlockNumber,
  targetLabel,
  latestBroadcastDeploymentAddresses = new Set()
) {
  if (!isCompleteDeploymentExport(chainDeployments)) {
    throw new Error(
      `Fresh deployment export for ${targetLabel} is not marked complete. Refusing to use raw broadcast data for target-chain artifacts.`
    );
  }

  const exportedContractNames = deploymentExportContractNames(chainDeployments);
  const missingContracts = REQUIRED_NON_LOCAL_DEPLOYMENT_EXPORT_CONTRACTS.filter(
    (contractName) => !exportedContractNames.has(contractName)
  );
  if (missingContracts.length > 0) {
    throw new Error(
      `Fresh deployment export for ${targetLabel} is missing required contracts: ${missingContracts.join(
        ", "
      )}. Refusing to use raw broadcast data for target-chain artifacts.`
    );
  }

  const exportBlockNumber = deploymentExportBlockNumber(chainDeployments);
  if (latestBroadcastBlockNumber === 0) {
    throw new Error(
      `No broadcast run data found for ${targetLabel}. Refusing to publish target-chain deployment artifacts.`
    );
  }
  if (exportBlockNumber < latestBroadcastBlockNumber) {
    const requiredExportAddresses =
      deploymentExportRequiredAddresses(chainDeployments);
    const allRequiredAddressesWereBroadcast = requiredExportAddresses.every(
      (address) => latestBroadcastDeploymentAddresses.has(address)
    );
    // On slow live-network broadcasts, the script-side block.number written by
    // vm.writeJson can lag the receipt blocks. Treat matching required
    // addresses from the latest broadcast as the freshness signal.
    if (allRequiredAddressesWereBroadcast) {
      return;
    }

    throw new Error(
      `Deployment export for ${targetLabel} is older than the latest broadcast deployment. Refusing to publish stale or partial target-chain artifacts.`
    );
  }
}

export function assertFreshTargetDeployment(
  allGeneratedContracts,
  existingContracts,
  deployments = {},
  latestBroadcastBlockNumbers = {},
  latestBroadcastDeploymentAddresses = {}
) {
  const deployTarget = process.env.DEPLOY_TARGET_NETWORK;
  if (!deployTarget) {
    const nonLocalChainIds = new Set([
      ...Object.keys(allGeneratedContracts),
      ...Object.keys(existingContracts),
    ]);

    for (const chainId of nonLocalChainIds) {
      if (
        !isNonLocalDeploymentChain(chainId) ||
        (!hasGeneratedContracts(allGeneratedContracts[chainId]) &&
          !hasGeneratedContracts(existingContracts[chainId]))
      ) {
        continue;
      }

      assertCompleteNonLocalDeploymentExport(
        deployments[chainId],
        latestBroadcastBlockNumbers[chainId] || 0,
        `chainId ${chainId}`,
        latestBroadcastDeploymentAddresses[chainId] || new Set()
      );
    }
    return;
  }

  const targetChainId = DEPLOY_TARGET_TO_CHAIN_ID[deployTarget];
  if (!targetChainId) return;

  if (deployTarget !== "localhost") {
    const chainId = String(targetChainId);
    assertCompleteNonLocalDeploymentExport(
      deployments[chainId],
      latestBroadcastBlockNumbers[chainId] || 0,
      `DEPLOY_TARGET_NETWORK='${deployTarget}' (chainId ${targetChainId})`,
      latestBroadcastDeploymentAddresses[chainId] || new Set()
    );
    return;
  }

  const generatedTargetContracts = allGeneratedContracts[String(targetChainId)];
  if (hasGeneratedContracts(generatedTargetContracts)) {
    return;
  }

  const existingTargetContracts = Object.keys(
    existingContracts[String(targetChainId)] || {}
  );
  const existingSummary = existingTargetContracts.length
    ? ` Existing entries for ${existingTargetContracts.join(
        ", "
      )} would be stale.`
    : "";

  throw new Error(
    `No fresh deployment data found for DEPLOY_TARGET_NETWORK='${deployTarget}' (chainId ${targetChainId}). Refusing to preserve existing shared deployment artifacts.${existingSummary}`
  );
}

export function filterGeneratedContractsForDeployTarget(allGeneratedContracts) {
  const deployTarget = process.env.DEPLOY_TARGET_NETWORK;
  const targetChainId = DEPLOY_TARGET_TO_CHAIN_ID[deployTarget];
  if (!deployTarget || !targetChainId) {
    return allGeneratedContracts;
  }

  const targetChainKey = String(targetChainId);
  const targetContracts = allGeneratedContracts[targetChainKey];
  return hasGeneratedContracts(targetContracts)
    ? { [targetChainKey]: targetContracts }
    : {};
}

function main() {
  const current_path_to_broadcast = join(__dirname, "..", "broadcast");
  const current_path_to_deployments = join(__dirname, "..", "deployments");

  const Deploymentchains = getFiles(current_path_to_deployments);
  const deployments = {};

  // Load existing deployments from deployments directory
  Deploymentchains.forEach((chain) => {
    if (!chain.endsWith(".json")) return;
    const deploymentFile = `${current_path_to_deployments}/${chain}`;
    chain = chain.slice(0, -5);
    var deploymentObject = JSON.parse(readFileSync(deploymentFile));
    deployments[chain] = deploymentObject;
  });

  // Process all deployments from all script folders
  const {
    contracts: allGeneratedContracts,
    deployers,
    deploymentsByAddress,
    latestBroadcastBlockNumbers,
    latestBroadcastDeploymentAddresses,
  } = processAllDeployments(current_path_to_broadcast);

  // Handle upgradeable proxies: the deployments JSON maps proxy addresses to
  // implementation contract names (e.g., { "0xProxy": "ContentToken" }).
  // We create entries using the proxy address + the implementation's ABI.
  // This is needed because the broadcast records proxies as "ERC1967Proxy"
  // (losing the implementation name), and deduplication collapses all
  // proxies into one entry.
  Object.entries(deployments).forEach(([chainId, chainDeployments]) => {
    if (typeof chainDeployments !== "object" || chainDeployments === null)
      return;

    Object.entries(chainDeployments).forEach(([address, contractName]) => {
      // Skip metadata entries like "networkName"
      if (!address.startsWith("0x")) return;

      const artifact = getArtifactOfContract(contractName);
      if (!artifact) return;

      if (!allGeneratedContracts[chainId]) {
        allGeneratedContracts[chainId] = {};
      }

      // Add/override: use the proxy address with the implementation's ABI
      allGeneratedContracts[chainId][contractName] = {
        address: address,
        abi: artifact.abi,
        inheritedFunctions: getInheritedFunctions(artifact),
        deployedOnBlock: (() => {
          const deployment = deploymentsByAddress.get(
            `${chainId}-${address.toLowerCase()}`
          );
          return (
            deployment?.deployedOnBlock &&
            Number(BigInt(deployment.deployedOnBlock))
          );
        })(),
      };
    });
  });

  const CONTRACTS_TARGET_DIR = join(__dirname, "..", "..", "contracts", "src");

  // Ensure target directories exist
  if (!existsSync(CONTRACTS_TARGET_DIR)) {
    mkdirSync(CONTRACTS_TARGET_DIR, { recursive: true });
  }

  const deployedContractsTargetFile = join(
    CONTRACTS_TARGET_DIR,
    "deployedContracts.ts"
  );
  const existingContracts = readExistingDeployedContracts(
    deployedContractsTargetFile
  );
  assertFreshTargetDeployment(
    allGeneratedContracts,
    existingContracts,
    deployments,
    latestBroadcastBlockNumbers,
    latestBroadcastDeploymentAddresses
  );
  const generatedContractsForPublish =
    filterGeneratedContractsForDeployTarget(allGeneratedContracts);
  const mergedContracts = {
    ...existingContracts,
    ...generatedContractsForPublish,
  };

  // Generate the shared deployedContracts content
  const fileContent = Object.entries(mergedContracts).reduce(
    (content, [chainId, chainConfig]) => {
      const cleanedChainConfig = Object.fromEntries(
        Object.entries(chainConfig).map(([contractName, contractData]) => {
          const { deploymentFile, deploymentScript, ...rest } = contractData;
          return [contractName, rest];
        })
      );
      return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(
        cleanedChainConfig,
        null,
        2
      )},`;
    },
    ""
  );

  // Write the files
  const fileTemplate = `
    ${generatedContractComment}
    import type { GenericContractsDeclaration } from "./types";

    const deployedContracts: GenericContractsDeclaration = {${fileContent}};

    export default deployedContracts;
  `;

  writeFileSync(
    deployedContractsTargetFile,
    format(fileTemplate, {
      parser: "typescript",
    })
  );

  console.log(
    `📝 Updated shared contract definition file on ${deployedContractsTargetFile}`
  );

  // --- Auto-generate ABI files for the shared contracts package ---
  generateAbiFiles();

  // --- Auto-update Ponder env with latest deployment for the selected target network ---
  updatePonderEnv(allGeneratedContracts, deployers);
}

/**
 * Maps chain IDs to Ponder network names.
 * Must match the network keys in packages/ponder/ponder.config.ts.
 */
const CHAIN_ID_TO_PONDER_NETWORK = {
  11142220: "celoSepolia",
  31337: "hardhat",
  42220: "celo",
};

const DEPLOY_TARGET_TO_PONDER_NETWORK = {
  localhost: "hardhat",
  celoSepolia: "celoSepolia",
  celo: "celo",
};

const DEPLOY_TARGET_TO_CHAIN_ID = {
  localhost: 31337,
  celoSepolia: 11142220,
  celo: 42220,
};

const PONDER_NETWORK_TO_CHAIN_ID = {
  hardhat: 31337,
  celoSepolia: 11142220,
  celo: 42220,
};

const PONDER_RPC_DEFAULTS = {
  hardhat: "http://127.0.0.1:8545",
  celoSepolia: "https://forno.celo-sepolia.celo-testnet.org",
  celo: "https://forno.celo.org",
};

const PONDER_CONTRACT_ENV_KEYS = {
  ContentRegistry: "PONDER_CONTENT_REGISTRY_ADDRESS",
  RoundVotingEngine: "PONDER_ROUND_VOTING_ENGINE_ADDRESS",
  RoundRewardDistributor: "PONDER_ROUND_REWARD_DISTRIBUTOR_ADDRESS",
  QuestionRewardPoolEscrow: "PONDER_QUESTION_REWARD_POOL_ESCROW_ADDRESS",
  FeedbackBonusEscrow: "PONDER_FEEDBACK_BONUS_ESCROW_ADDRESS",
  CategoryRegistry: "PONDER_CATEGORY_REGISTRY_ADDRESS",
  ProfileRegistry: "PONDER_PROFILE_REGISTRY_ADDRESS",
  FrontendRegistry: "PONDER_FRONTEND_REGISTRY_ADDRESS",
  VoterIdNFT: "PONDER_VOTER_ID_NFT_ADDRESS",
  MeshReputation: "PONDER_MREP_ADDRESS",
  ParticipationPool: "PONDER_PARTICIPATION_POOL_ADDRESS",
  TimelockController: "PONDER_TIMELOCK_ADDRESS",
};

const PONDER_START_BLOCK_ENV_KEYS = {
  ContentRegistry: "PONDER_CONTENT_REGISTRY_START_BLOCK",
  RoundVotingEngine: "PONDER_ROUND_VOTING_ENGINE_START_BLOCK",
  RoundRewardDistributor: "PONDER_ROUND_REWARD_DISTRIBUTOR_START_BLOCK",
  QuestionRewardPoolEscrow: "PONDER_QUESTION_REWARD_POOL_ESCROW_START_BLOCK",
  FeedbackBonusEscrow: "PONDER_FEEDBACK_BONUS_ESCROW_START_BLOCK",
  CategoryRegistry: "PONDER_CATEGORY_REGISTRY_START_BLOCK",
  ProfileRegistry: "PONDER_PROFILE_REGISTRY_START_BLOCK",
  FrontendRegistry: "PONDER_FRONTEND_REGISTRY_START_BLOCK",
  VoterIdNFT: "PONDER_VOTER_ID_NFT_START_BLOCK",
  MeshReputation: "PONDER_MREP_START_BLOCK",
  ParticipationPool: "PONDER_PARTICIPATION_POOL_START_BLOCK",
  TimelockController: "PONDER_TIMELOCK_START_BLOCK",
};

function parseEnvFile(content) {
  const env = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx <= 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    env[key] = value;
  }
  return env;
}

function serializeEnvFile(env) {
  const header = [
    "# Auto-generated by packages/foundry/scripts-js/generateTsAbis.js",
    "# Re-run `yarn deploy` to refresh these values.",
    "",
  ];

  const body = Object.keys(env)
    .sort()
    .map((key) => `${key}=${env[key]}`);

  return `${header.join("\n")}${body.join("\n")}\n`;
}

function updatePonderEnv(allGeneratedContracts, deployers = {}) {
  const deployTarget = process.env.DEPLOY_TARGET_NETWORK;
  const ponderNetwork = DEPLOY_TARGET_TO_PONDER_NETWORK[deployTarget];

  if (!ponderNetwork) {
    console.warn(
      `⚠️  Could not map DEPLOY_TARGET_NETWORK='${deployTarget}' to a Ponder network; skipping Ponder env sync.`
    );
    return;
  }

  const chainId = PONDER_NETWORK_TO_CHAIN_ID[ponderNetwork];
  const chainContracts = allGeneratedContracts[String(chainId)];
  if (!chainContracts) {
    console.warn(
      `⚠️  No generated contracts found for chainId ${chainId}; skipping Ponder env sync.`
    );
    return;
  }

  const ponderEnvPath = join(__dirname, "..", "..", "ponder", ".env.local");
  const existingEnv = existsSync(ponderEnvPath)
    ? parseEnvFile(readFileSync(ponderEnvPath, "utf8"))
    : {};

  existingEnv.PONDER_NETWORK = ponderNetwork;

  const rpcEnvKey = `PONDER_RPC_URL_${chainId}`;
  if (!existingEnv[rpcEnvKey]) {
    existingEnv[rpcEnvKey] = PONDER_RPC_DEFAULTS[ponderNetwork];
  }

  const deployedBlocks = Object.values(chainContracts)
    .map((contract) => Number(contract?.deployedOnBlock || 0))
    .filter((blockNumber) => Number.isFinite(blockNumber) && blockNumber > 0);
  const chainStartBlock =
    deployedBlocks.length > 0 ? Math.min(...deployedBlocks) : 0;

  // Exclude deployer from token holder tracking (leaderboard)
  const deployerAddress = deployers[String(chainId)];
  if (deployerAddress) {
    existingEnv["PONDER_DEPLOYER_ADDRESS"] = deployerAddress;
  }

  const updatedContracts = [];
  const removedContracts = [];
  for (const [contractName, addressEnvKey] of Object.entries(
    PONDER_CONTRACT_ENV_KEYS
  )) {
    const contractData = chainContracts[contractName];
    const blockEnvKey = PONDER_START_BLOCK_ENV_KEYS[contractName];
    if (!contractData?.address) {
      delete existingEnv[addressEnvKey];
      delete existingEnv[blockEnvKey];
      removedContracts.push(contractName);
      continue;
    }

    existingEnv[addressEnvKey] = contractData.address;

    const startBlock = Number(
      contractData.deployedOnBlock || chainStartBlock || 0
    );
    if (startBlock > 0) {
      existingEnv[blockEnvKey] = String(startBlock);
    }

    updatedContracts.push(contractName);
  }

  writeFileSync(ponderEnvPath, serializeEnvFile(existingEnv));
  console.log(
    `📝 Updated Ponder .env.local (${ponderNetwork}, chainId ${chainId}) with latest deployment addresses: ${updatedContracts.join(
      ", "
    )}`
  );
  if (removedContracts.length > 0) {
    console.log(
      `🧹 Removed stale Ponder .env.local entries with no shared deployment artifact: ${removedContracts.join(
        ", "
      )}`
    );
  }
}

/**
 * Contract-to-ABI-target mapping.
 * ABI files are generated once into the shared contracts package.
 * Paths are relative to the monorepo root (packages/).
 */
const ABI_TARGETS = [
  {
    contract: "RoundVotingEngine",
    targets: ["contracts/src/abis"],
  },
  {
    contract: "ContentRegistry",
    targets: ["contracts/src/abis"],
  },
  { contract: "CategoryRegistry", targets: ["contracts/src/abis"] },
  { contract: "MeshReputation", targets: ["contracts/src/abis"] },
  { contract: "HumanReputation", targets: ["contracts/src/abis"] },
  { contract: "VoterIdNFT", targets: ["contracts/src/abis"] },
  { contract: "FrontendRegistry", targets: ["contracts/src/abis"] },
  { contract: "RoundRewardDistributor", targets: ["contracts/src/abis"] },
  { contract: "QuestionRewardPoolEscrow", targets: ["contracts/src/abis"] },
  { contract: "X402QuestionSubmitter", targets: ["contracts/src/abis"] },
  { contract: "FeedbackBonusEscrow", targets: ["contracts/src/abis"] },
  { contract: "ProfileRegistry", targets: ["contracts/src/abis"] },
  { contract: "ProtocolConfig", targets: ["contracts/src/abis"] },
  { contract: "RaterRegistry", targets: ["contracts/src/abis"] },
  { contract: "RaterDeclarationRegistry", targets: ["contracts/src/abis"] },
  { contract: "HumanFaucet", targets: ["contracts/src/abis"] },
  { contract: "ParticipationPool", targets: ["contracts/src/abis"] },
  { contract: "TimelockController", targets: ["contracts/src/abis"] },
  { contract: "CuryoGovernor", targets: ["contracts/src/abis"] },
];

function generateAbiFiles() {
  const packagesDir = join(__dirname, "..", "..");
  let totalWritten = 0;

  for (const { contract, targets } of ABI_TARGETS) {
    const artifact = getArtifactOfContract(contract);
    if (!artifact) {
      console.warn(
        `⚠️  No artifact found for ${contract} — skipping ABI generation`
      );
      continue;
    }

    const abiJson = JSON.stringify(artifact.abi, null, 2);
    const fileContent = `export const ${contract}Abi = ${abiJson} as const;\n`;

    for (const target of targets) {
      const targetDir = join(packagesDir, target);
      if (!existsSync(targetDir)) {
        mkdirSync(targetDir, { recursive: true });
      }
      writeFileSync(join(targetDir, `${contract}Abi.ts`), fileContent);
      totalWritten++;
    }
  }

  console.log(
    `📝 Generated ${totalWritten} ABI files across ${ABI_TARGETS.reduce(
      (n, t) => n + t.targets.length,
      0
    )} shared targets`
  );

  // Drift detection: warn if a contract has Ponder env mapping but no ABI target
  const abiContractNames = new Set(ABI_TARGETS.map((t) => t.contract));
  for (const contractName of Object.keys(PONDER_CONTRACT_ENV_KEYS)) {
    if (!abiContractNames.has(contractName)) {
      console.warn(
        `⚠️  Contract "${contractName}" has Ponder env mapping but no ABI target — add it to ABI_TARGETS to generate ABI files.`
      );
    }
  }
}

if (
  process.argv[1] &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1])
) {
  try {
    main();
  } catch (error) {
    console.error("Error:", error);
    process.exitCode = 1;
  }
}
