[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/keeper/Dockerfile"
watchPatterns = [
  ".yarn/**",
  ".yarnrc.yml",
  "package.json",
  "yarn.lock",
  "scripts/clean-package-dist.mjs",
  "scripts/fix-esm-extensions.mjs",
  "scripts/write-cjs-package-json.mjs",
  "packages/contracts/**",
  "packages/keeper/**",
  "packages/node-utils/**",
]

[deploy]
startCommand = "NODE_ENV=production yarn workspace @rateloop/keeper start:built-workspace-deps"
