[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/keeper/Dockerfile"
watchPatterns = [
  ".yarn/**",
  ".yarnrc.yml",
  "package.json",
  "yarn.lock",
  "scripts/clean-package-dist.mjs",
  "scripts/fix-esm-extensions.mjs",
  "scripts/with-workspace-dist-lock.mjs",
  "scripts/write-cjs-package-json.mjs",
  "packages/contracts/**",
  "packages/keeper/**",
  "packages/node-utils/**",
]

[deploy]
startCommand = "sh ./docker-entrypoint.sh"
healthcheckPath = "/live"
healthcheckTimeout = 120
