[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/keeper/Dockerfile"
watchPatterns = [
  ".yarn/**",
  ".yarnrc.yml",
  "package.json",
  "yarn.lock",
  "scripts/clean-package-dist.mjs",
  "scripts/fix-esm-extensions.mjs",
  "scripts/with-workspace-dist-lock.mjs",
  "scripts/write-cjs-package-json.mjs",
  "packages/keeper/**",
  "packages/node-utils/**",
]

[deploy]
startCommand = "yarn start:built-dist"
healthcheckPath = "/ready"
healthcheckTimeout = 120

[deploy.multiRegionConfig]
"europe-west4-drams3a" = { numReplicas = 1 }
