import React from "react";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { translatePublicString } from "~~/components/docs/LocalizedPublicContent";

const require = createRequire(import.meta.url);
const { renderToStaticMarkup } = require("react-dom/server") as {
  renderToStaticMarkup: (element: React.ReactElement) => string;
};

test("evidence docs explain exact artifacts, checks, mappings, and boundaries", async () => {
  (globalThis as typeof globalThis & { React: typeof React }).React = React;
  const { COMPLIANCE_ROWS, default: EvidencePage } = await import("./page");
  const { assuranceComplianceMap } = await import("~~/config/assuranceComplianceMap.mjs");
  const html = renderToStaticMarkup(<EvidencePage />).replace(/\s+/g, " ");

  assert.match(html, /Evidence.*rateloop-text-gradient.*Reference/i);
  assert.match(html, /At a glance/i);
  assert.match(html, /aria-label="On this page"/i);
  for (const href of [
    "#shared-responsibility",
    "#packet",
    "#commissioned-paid-panels",
    "#verify",
    "#exports",
    "#compliance-map",
  ]) {
    assert.match(html, new RegExp(`href="${href}"`));
  }
  assert.doesNotMatch(html, /What this is not|RateLoop never claims/i);
  assert.match(html, /Shared responsibility/i);
  assert.match(html, /Your people provide oversight\. RateLoop records configured review activity and its evidence\./);
  assert.match(html, /RateLoop does not determine which legal requirements apply or establish compliance\./);
  assert.match(html, /Requirement.*RateLoop provides.*You remain responsible for/i);
  for (const requirement of [
    "Art 14(4)(a) · Monitor",
    "Art 14(4)(b) · Automation bias",
    "Art 14(4)(c) · Interpret",
    "Art 14(4)(d) · Override",
    "Art 14(4)(e) · Stop",
    "Art 26(2) · Assignment",
    "Art 26(5) · Monitoring",
    "Art 26(6) · Log retention",
    "Art 4 · AI literacy",
  ]) {
    assert.match(html, new RegExp(requirement.replace(/[()·]/g, "\\$&")));
  }
  assert.doesNotMatch(html, /Verified host enforcement can hold output undelivered until a person decides/i);
  assert.match(
    html,
    /Advisory Codex, plugin, and MCP integrations record lifecycle state but do not verify withholding/i,
  );
  assert.match(html, /no available host currently provides verified delivery enforcement/i);
  assert.match(html, /per-output override records with required reasons/i);
  assert.match(html, /Blinded reviewer judgments/i);
  assert.match(html, /surfaced disagreement before the decision/i);
  assert.match(html, /attestation records — competence basis, training completed, authority granted/i);
  assert.match(html, /six-month floor for RateLoop review records/i);
  assert.match(html, /Retaining logs generated by your high-risk AI system and under your control/i);
  assert.match(html, /RateLoop(?:&#x27;|')s floor does not satisfy that duty/i);
  assert.match(html, /Exportable training and calibration records/i);
  assert.match(html, /Choosing those natural persons and ensuring they are competent, trained, and authorized/i);
  assert.match(html, /Advisory integrations do not control output delivery/i);
  assert.match(html, /only a verified host adapter that owns the delivery boundary can enforce a held review state/i);
  assert.match(html, /no host currently holds that tier/i);
  assert.match(html, /Model identity is labelled host-reported/i);
  assert.match(html, /does not independently verify which model produced an output/i);
  assert.match(html, /SOC 2 \/ ISO \/ HIPAA \/ residency attestations it does not hold/i);
  assert.match(html, /evidence method is to publish the boundary beside every control/i);
  assert.match(html, /limits are part of the verification record, not an apology/i);
  assert.match(html, /no evidence export by itself makes anyone compliant/i);
  assert.match(html, /rateloop\.human-assurance\.evidence\.v4/i);
  assert.match(html, /Complete synthetic packet example/i);
  assert.match(html, /Enable the new response policy for a 10% rollout/i);
  assert.match(html, /does not contain or sign the separate owner decision/i);
  assert.match(html, /Download packet/i);
  assert.match(html, /Download synthetic key pin/i);
  assert.match(html, /ed25519:2d5798c16bafaed29bdbcca0/i);
  assert.match(html, /only the trust anchor for the synthetic example/i);
  assert.doesNotMatch(html, /Redacted packet example/i);
  assert.match(html, /Frozen scope.*Review context.*Judgment evidence.*Available references and limits/i);
  assert.match(html, /reviewer identities and raw or decryptable rationales are excluded/i);
  assert.match(html, /Commissioned paid-panel methodology/i);
  assert.match(html, /not organic consumer feedback, a customer testimonial, an endorsement/i);
  assert.match(html, /does not infer a view held by non-participants/i);
  assert.match(html, /must not relabel paid reviewer feedback as unsolicited customer or consumer feedback/i);
  assert.match(html, /evidence:verify.*--public-key.*--key-id/i);
  assert.match(html, /audit:verify.*--expected-head/i);
  assert.match(html, /attestation:verify.*--signer-public-key.*--signer-key-id.*--rekor-public-key.*--tsa-ca/is);
  assert.match(html, /independently selected Base RPC or indexer/i);
  assert.match(html, /does not embed a complete transaction receipt/i);
  assert.match(html, /Every completed decision-packet attestation includes a Rekor bundle/i);
  assert.match(html, /authenticated checkpoint/i);
  assert.match(html, /missing or invalid bundle makes the witness incomplete/i);
  assert.doesNotMatch(html, /absent bundle means there is no Rekor receipt/i);
  assert.match(html, /absent token means there is no TSA receipt/i);
  assert.match(html, /assurance\/coverage\/export/i);
  assert.match(html, /assurance\/trusted-keys/i);
  assert.match(
    html,
    /Scheduled enforcement removes due private artifact content and access logs unless a legal hold applies/i,
  );
  assert.match(html, /canonical audit chain remain as integrity records/i);
  assert.equal(COMPLIANCE_ROWS.length, assuranceComplianceMap.mappings.length);
  for (const mapping of assuranceComplianceMap.mappings) {
    const row = COMPLIANCE_ROWS.find(candidate => candidate.id === mapping.id);
    assert.ok(row, `missing rendered mapping ${mapping.id}`);
    assert.equal(row.boundary, mapping.nonClaim);
    assert.ok(html.includes(mapping.nonClaim.replaceAll("'", "&#x27;")), `missing rendered non-claim ${mapping.id}`);
  }
  assert.match(html, /ISO\/IEC 42001:2023.*A\.6/i);
  assert.match(html, /Article 26\(5\)-\(6\)/i);
  assert.doesNotMatch(html, /Article 12|Article 72|17 CFR 240\.17a-4|Rule 17a-4/i);
  assert.doesNotMatch(html, /26\(1\)/);
  assert.match(html, /NIST AI Risk Management Framework.*MEASURE/i);
  assert.match(html, /Regulatory Notice 24-09/i);
  assert.match(html, /Rule 3110/i);
  assert.match(html, /supports evidence for/i);
  assert.match(html, /Framework cross-reference/i);
  assert.match(html, /public verification-key endpoint/i);
  assert.match(html, /needs no RateLoop account/i);
  assert.match(html, /rateloop-human-assurance-component-definition\.oscal\.json/i);
  assert.doesNotMatch(html, /trust status|compliance-ready|certified RateLoop/i);
  assert.doesNotMatch(html, /RateLoop provides the instrument — and the proof/i);
});

test("machine docs mirror evidence boundaries and are linked from agent setup", () => {
  const evidence = readFileSync(
    fileURLToPath(new URL("../../../../../public/docs/evidence.md", import.meta.url)),
    "utf8",
  );
  const connection = readFileSync(
    fileURLToPath(new URL("../../../../../public/docs/agent-connection.md", import.meta.url)),
    "utf8",
  );

  assert.match(evidence, /rateloop\.human-assurance\.evidence\.v4/);
  assert.match(evidence, /Complete synthetic packet example/i);
  assert.match(evidence, /Enable the new response policy for a 10% rollout/i);
  assert.match(evidence, /does not contain or sign the separate owner decision/i);
  assert.match(evidence, /synthetic-evidence-v4\.json/);
  assert.match(evidence, /synthetic-evidence-v4\.spki\.txt/);
  assert.match(evidence, /ed25519:2d5798c16bafaed29bdbcca0/);
  assert.doesNotMatch(evidence, /Redacted shape/i);
  assert.match(evidence, /Commissioned paid-panel methodology/i);
  assert.match(evidence, /not organic consumer feedback, a customer testimonial, an\s+endorsement/i);
  assert.match(evidence, /must not relabel paid reviewer feedback as unsolicited customer or consumer feedback/i);
  assert.match(evidence, /Model identity is\s+labelled host-reported/i);
  assert.match(evidence, /does not independently verify which model produced an output/i);
  assert.match(evidence, /evidence:verify.*--public-key.*--key-id/is);
  assert.match(evidence, /audit:verify.*--expected-head/is);
  assert.match(evidence, /attestation:verify.*--signer-public-key.*--rekor-public-key.*--tsa-ca/is);
  assert.match(evidence, /ISO\/IEC 42001:2023.*A\.6 including A\.6\.2\.8, and A\.9\.2/is);
  assert.match(evidence, /Articles 14\(3\)\(b\), 14\(4\), 26\(2\), 26\(5\)-\(6\), and 73/);
  assert.match(evidence, /six-month floor for RateLoop review records/i);
  assert.match(evidence, /Retaining logs generated by your high-risk AI system and under your control/i);
  assert.match(evidence, /RateLoop's floor does not satisfy that duty/i);
  assert.doesNotMatch(evidence, /Article 12|Article 72|17 CFR 240\.17a-4|Rule 17a-4/i);
  assert.match(
    evidence,
    /Your people provide oversight\. RateLoop records configured review activity and its evidence\./,
  );
  assert.match(evidence, /You remain responsible for/);
  assert.match(evidence, /Advisory integrations do not control output delivery/i);
  assert.match(
    evidence,
    /only a verified host adapter that\s+owns the delivery boundary can enforce a held review state/i,
  );
  assert.match(evidence, /No host currently holds that tier/i);
  assert.doesNotMatch(evidence, /What this is not|RateLoop never claims|26\(1\)/);
  assert.match(
    evidence,
    /Scheduled enforcement removes due private artifact[\s\S]*content and access logs unless a legal hold applies/i,
  );
  assert.match(evidence, /canonical audit chain remain as integrity records/i);
  assert.match(evidence, /rateloop-human-assurance-component-definition\.oscal\.json/);
  assert.doesNotMatch(evidence, /RateLoop provides the instrument — and the proof/i);
  assert.match(connection, /\[`evidence\.md`\]\(\.\/evidence\.md\)/);
  assert.match(connection, /\[`\/docs\/evidence`\]\(\/docs\/evidence\)/);
  assert.match(connection, /MCP does not define\s+a universal client configuration file/i);
  assert.doesNotMatch(connection, /common `mcpServers` shape/);
  assert.match(connection, /No protected-workspace host is yet in the \*\*Release-tested\*\* tier/);
  assert.match(connection, /Claude Code[\s\S]*claude mcp add --scope user --transport http rateloop-workspace/);
  assert.match(connection, /GitHub Copilot Chat in local VS Code[\s\S]*"servers"/);
  assert.match(connection, /Gemini CLI[\s\S]*gemini mcp add --scope user --transport http rateloop-workspace/);
  assert.match(connection, /"httpUrl": "https:\/\/rateloop-tokenless\.vercel\.app\/api\/agent\/v1\/mcp"/);
  assert.match(connection, /GitHub Copilot cloud agent and code review[\s\S]*cannot connect to a remote OAuth MCP/i);
  assert.match(connection, /should not be presented with an install link, client ID, redirect URI, or copied JSON/i);
});

test("the synthetic example has a German recipient path", () => {
  assert.equal(
    translatePublicString("Complete synthetic packet example", "de", "docs"),
    "Vollständiges synthetisches Paketbeispiel",
  );
  assert.equal(translatePublicString("Download packet", "de", "docs"), "Paket herunterladen");
  assert.match(
    translatePublicString(
      "This pin is only the trust anchor for the synthetic example. It is not a RateLoop production signing key and does not appear in the hosted verification-key endpoint.",
      "de",
      "docs",
    ),
    /kein RateLoop-Produktionsschlüssel/u,
  );
});
