CREATE TABLE "tokenless_assurance_cohorts" (
  "cohort_id" text PRIMARY KEY NOT NULL,
  "project_id" text NOT NULL REFERENCES "tokenless_assurance_projects"("project_id"),
  "name" text NOT NULL,
  "source" text NOT NULL,
  "selection" text NOT NULL,
  "capacity" integer NOT NULL,
  "active_reservations" integer DEFAULT 0 NOT NULL,
  "qualification_rules_json" text NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "created_by" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "updated_at" timestamp with time zone NOT NULL,
  CONSTRAINT "tokenless_assurance_cohorts_project_cohort_unique" UNIQUE("project_id", "cohort_id"),
  CONSTRAINT "tokenless_assurance_cohorts_source_check" CHECK ("source" IN ('customer_invited', 'rateloop_network', 'sandbox')),
  CONSTRAINT "tokenless_assurance_cohorts_selection_check" CHECK ("selection" IN ('customer_named', 'randomized')),
  CONSTRAINT "tokenless_assurance_cohorts_capacity_check" CHECK ("capacity" BETWEEN 1 AND 10000),
  CONSTRAINT "tokenless_assurance_cohorts_reservations_check" CHECK ("active_reservations" BETWEEN 0 AND "capacity")
);--> statement-breakpoint
CREATE INDEX "tokenless_assurance_cohorts_project_source_idx" ON "tokenless_assurance_cohorts" USING btree ("project_id", "source", "status");--> statement-breakpoint
CREATE TABLE "tokenless_assurance_cohort_reviewers" (
  "project_id" text NOT NULL,
  "cohort_id" text NOT NULL,
  "reviewer_account_address" text NOT NULL,
  "qualification_provenance_json" text NOT NULL,
  "qualification_expires_at" timestamp with time zone,
  "maximum_active_assignments" integer DEFAULT 1 NOT NULL,
  "active_reservations" integer DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "created_by" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "updated_at" timestamp with time zone NOT NULL,
  PRIMARY KEY ("project_id", "cohort_id", "reviewer_account_address"),
  FOREIGN KEY ("project_id", "cohort_id") REFERENCES "tokenless_assurance_cohorts"("project_id", "cohort_id"),
  CONSTRAINT "tokenless_assurance_cohort_reviewers_capacity_check" CHECK ("maximum_active_assignments" BETWEEN 1 AND 100),
  CONSTRAINT "tokenless_assurance_cohort_reviewers_reservations_check" CHECK ("active_reservations" BETWEEN 0 AND "maximum_active_assignments")
);--> statement-breakpoint
CREATE INDEX "tokenless_assurance_cohort_reviewers_account_idx" ON "tokenless_assurance_cohort_reviewers" USING btree ("reviewer_account_address", "status", "qualification_expires_at");--> statement-breakpoint
CREATE TABLE "tokenless_assurance_reviewer_invitations" (
  "invitation_id" text PRIMARY KEY NOT NULL,
  "workspace_id" text NOT NULL REFERENCES "tokenless_workspaces"("workspace_id"),
  "project_id" text NOT NULL REFERENCES "tokenless_assurance_projects"("project_id"),
  "cohort_id" text NOT NULL,
  "token_hash" text NOT NULL,
  "intended_account_address" text,
  "qualification_provenance_json" text NOT NULL,
  "maximum_active_assignments" integer DEFAULT 1 NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "redeemed_at" timestamp with time zone,
  "redeemed_by_account_address" text,
  "revoked_at" timestamp with time zone,
  "created_by" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  FOREIGN KEY ("project_id", "cohort_id") REFERENCES "tokenless_assurance_cohorts"("project_id", "cohort_id"),
  CONSTRAINT "tokenless_assurance_reviewer_invitations_token_unique" UNIQUE("token_hash"),
  CONSTRAINT "tokenless_assurance_reviewer_invitations_capacity_check" CHECK ("maximum_active_assignments" BETWEEN 1 AND 100)
);--> statement-breakpoint
CREATE INDEX "tokenless_assurance_reviewer_invitations_project_state_idx" ON "tokenless_assurance_reviewer_invitations" USING btree ("workspace_id", "project_id", "expires_at", "redeemed_at", "revoked_at");--> statement-breakpoint
CREATE TABLE "tokenless_assurance_run_subpanels" (
  "subpanel_id" text PRIMARY KEY NOT NULL,
  "workspace_id" text NOT NULL REFERENCES "tokenless_workspaces"("workspace_id"),
  "project_id" text NOT NULL REFERENCES "tokenless_assurance_projects"("project_id"),
  "run_id" text NOT NULL REFERENCES "tokenless_assurance_runs"("run_id"),
  "cohort_id" text NOT NULL,
  "source" text NOT NULL,
  "selection" text NOT NULL,
  "target_count" integer NOT NULL,
  "active_reservations" integer DEFAULT 0 NOT NULL,
  "policy_id" text NOT NULL,
  "policy_version" integer NOT NULL,
  "policy_hash" text NOT NULL,
  "run_manifest_hash" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  FOREIGN KEY ("project_id", "cohort_id") REFERENCES "tokenless_assurance_cohorts"("project_id", "cohort_id"),
  FOREIGN KEY ("policy_id", "policy_version") REFERENCES "tokenless_assurance_audience_policies"("policy_id", "version"),
  CONSTRAINT "tokenless_assurance_run_subpanels_run_cohort_unique" UNIQUE("run_id", "cohort_id"),
  CONSTRAINT "tokenless_assurance_run_subpanels_source_check" CHECK ("source" IN ('customer_invited', 'rateloop_network', 'sandbox')),
  CONSTRAINT "tokenless_assurance_run_subpanels_selection_check" CHECK ("selection" IN ('customer_named', 'randomized')),
  CONSTRAINT "tokenless_assurance_run_subpanels_target_check" CHECK ("target_count" BETWEEN 1 AND 10000),
  CONSTRAINT "tokenless_assurance_run_subpanels_reservations_check" CHECK ("active_reservations" BETWEEN 0 AND "target_count")
);--> statement-breakpoint
CREATE INDEX "tokenless_assurance_run_subpanels_run_source_idx" ON "tokenless_assurance_run_subpanels" USING btree ("run_id", "source");--> statement-breakpoint
CREATE TABLE "tokenless_assurance_assignments" (
  "assignment_id" text PRIMARY KEY NOT NULL,
  "workspace_id" text NOT NULL REFERENCES "tokenless_workspaces"("workspace_id"),
  "project_id" text NOT NULL REFERENCES "tokenless_assurance_projects"("project_id"),
  "run_id" text NOT NULL REFERENCES "tokenless_assurance_runs"("run_id"),
  "subpanel_id" text NOT NULL REFERENCES "tokenless_assurance_run_subpanels"("subpanel_id"),
  "cohort_id" text NOT NULL,
  "reviewer_account_address" text NOT NULL,
  "source" text NOT NULL,
  "selection" text NOT NULL,
  "status" text DEFAULT 'reserved' NOT NULL,
  "confidentiality_terms_hash" text NOT NULL,
  "confidentiality_accepted_at" timestamp with time zone,
  "qualification_provenance_json" text NOT NULL,
  "blinding_json" text NOT NULL,
  "paid_assignment" boolean NOT NULL,
  "paid_eligibility_checked_at" timestamp with time zone,
  "voucher_marker" text,
  "reservation_expires_at" timestamp with time zone NOT NULL,
  "assignment_expires_at" timestamp with time zone,
  "lease_issuer_account_address" text NOT NULL,
  "lease_state" text DEFAULT 'pending' NOT NULL,
  "recovery_count" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "accepted_at" timestamp with time zone,
  "updated_at" timestamp with time zone NOT NULL,
  FOREIGN KEY ("project_id", "cohort_id", "reviewer_account_address") REFERENCES "tokenless_assurance_cohort_reviewers"("project_id", "cohort_id", "reviewer_account_address"),
  CONSTRAINT "tokenless_assurance_assignments_run_reviewer_unique" UNIQUE("run_id", "reviewer_account_address"),
  CONSTRAINT "tokenless_assurance_assignments_source_check" CHECK ("source" IN ('customer_invited', 'rateloop_network', 'sandbox')),
  CONSTRAINT "tokenless_assurance_assignments_selection_check" CHECK ("selection" IN ('customer_named', 'randomized')),
  CONSTRAINT "tokenless_assurance_assignments_status_check" CHECK ("status" IN ('reserved', 'accepted', 'expired', 'released', 'completed')),
  CONSTRAINT "tokenless_assurance_assignments_lease_state_check" CHECK ("lease_state" IN ('pending', 'issued', 'failed', 'expired')),
  CONSTRAINT "tokenless_assurance_assignments_paid_check" CHECK (("paid_assignment" = false AND "paid_eligibility_checked_at" IS NULL AND "voucher_marker" IS NULL) OR ("paid_assignment" = true AND "paid_eligibility_checked_at" IS NOT NULL)),
  CONSTRAINT "tokenless_assurance_assignments_recovery_check" CHECK ("recovery_count" BETWEEN 0 AND 20)
);--> statement-breakpoint
CREATE INDEX "tokenless_assurance_assignments_reviewer_status_idx" ON "tokenless_assurance_assignments" USING btree ("reviewer_account_address", "status", "reservation_expires_at");--> statement-breakpoint
CREATE INDEX "tokenless_assurance_assignments_run_status_idx" ON "tokenless_assurance_assignments" USING btree ("run_id", "status", "updated_at");
