import type { Abi } from "viem";

const roundComponents = [
  { name: "funder", type: "address" },
  { name: "contentId", type: "bytes32" },
  { name: "termsHash", type: "bytes32" },
  { name: "beaconNetworkHash", type: "bytes32" },
  { name: "feeRecipient", type: "address" },
  { name: "bountyAmount", type: "uint256" },
  { name: "feeAmount", type: "uint256" },
  { name: "attemptReserve", type: "uint256" },
  { name: "attemptCompensation", type: "uint256" },
  { name: "fixedBasePay", type: "uint256" },
  { name: "maximumBonus", type: "uint256" },
  { name: "compensationPerRecipient", type: "uint256" },
  { name: "totalRbtsScoreBps", type: "uint256" },
  { name: "totalFinalizedLiability", type: "uint256" },
  { name: "totalPaid", type: "uint256" },
  { name: "entropyBlock", type: "uint256" },
  { name: "revealSetXor", type: "bytes32" },
  { name: "revealSetSum", type: "uint256" },
  { name: "scoringSeed", type: "bytes32" },
  { name: "commitDeadline", type: "uint64" },
  { name: "revealDeadline", type: "uint64" },
  { name: "beaconFailureDeadline", type: "uint64" },
  { name: "beaconRound", type: "uint64" },
  { name: "claimGracePeriod", type: "uint64" },
  { name: "claimDeadline", type: "uint256" },
  { name: "minimumReveals", type: "uint32" },
  { name: "maximumCommits", type: "uint32" },
  { name: "admissionPolicyHash", type: "bytes32" },
  { name: "commitCount", type: "uint32" },
  { name: "revealCount", type: "uint32" },
  { name: "compensatedRevealCount", type: "uint32" },
  { name: "frozenRevealCount", type: "uint32" },
  { name: "aggregateCursor", type: "uint32" },
  { name: "scoreCursor", type: "uint32" },
  { name: "upVotes", type: "uint32" },
  { name: "state", type: "uint8" },
  { name: "scoringMode", type: "uint8" },
  { name: "staleReturned", type: "bool" },
] as const;

const commitComponents = [
  { name: "roundId", type: "uint256" },
  { name: "voteKey", type: "address" },
  { name: "sealedCommitment", type: "bytes32" },
  { name: "sealedPayloadHash", type: "bytes32" },
  { name: "payoutCommitment", type: "bytes32" },
  { name: "responseHash", type: "bytes32" },
  { name: "referenceCommitKey", type: "bytes32" },
  { name: "peerCommitKey", type: "bytes32" },
  { name: "finalizedPayout", type: "uint256" },
  { name: "predictedUpBps", type: "uint16" },
  { name: "informationScoreBps", type: "uint16" },
  { name: "predictionScoreBps", type: "uint16" },
  { name: "rbtsScoreBps", type: "uint16" },
  { name: "vote", type: "uint8" },
  { name: "revealed", type: "bool" },
  { name: "claimed", type: "bool" },
] as const;

export const tokenlessPanelAbi = [
  {
    type: "event",
    name: "RoundCreated",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "funder", type: "address", indexed: true },
      { name: "contentId", type: "bytes32", indexed: true },
      { name: "termsHash", type: "bytes32", indexed: false },
      { name: "admissionPolicyHash", type: "bytes32", indexed: false },
      { name: "bountyAmount", type: "uint256", indexed: false },
      { name: "feeAmount", type: "uint256", indexed: false },
      { name: "attemptReserve", type: "uint256", indexed: false },
      { name: "fixedBasePay", type: "uint256", indexed: false },
      { name: "maximumBonus", type: "uint256", indexed: false },
      { name: "scoringVersion", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CommitAccepted",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "commitKey", type: "bytes32", indexed: true },
      { name: "nullifier", type: "bytes32", indexed: true },
      { name: "sealedPayload", type: "bytes", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RevealAccepted",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "commitKey", type: "bytes32", indexed: true },
      { name: "vote", type: "uint8", indexed: false },
      { name: "predictedUpBps", type: "uint16", indexed: false },
      { name: "responseHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SettlementBegun",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "frozenRevealCount", type: "uint32", indexed: false },
      { name: "entropyBlock", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ScoringSeedFinalized",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "mode", type: "uint8", indexed: true },
      { name: "entropyBlock", type: "uint256", indexed: false },
      { name: "entropy", type: "bytes32", indexed: false },
      { name: "scoringSeed", type: "bytes32", indexed: false },
      { name: "revealSetXor", type: "bytes32", indexed: false },
      { name: "revealSetSum", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RevealScored",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "commitKey", type: "bytes32", indexed: true },
      { name: "referenceCommitKey", type: "bytes32", indexed: false },
      { name: "peerCommitKey", type: "bytes32", indexed: false },
      { name: "informationScoreBps", type: "uint16", indexed: false },
      { name: "predictionScoreBps", type: "uint16", indexed: false },
      { name: "rbtsScoreBps", type: "uint16", indexed: false },
      { name: "finalizedPayout", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SettlementProgressed",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "state", type: "uint8", indexed: true },
      { name: "cursor", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RoundFinalized",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "mode", type: "uint8", indexed: true },
      { name: "totalRbtsScoreBps", type: "uint256", indexed: false },
      { name: "totalFinalizedLiability", type: "uint256", indexed: false },
      { name: "funderRefund", type: "uint256", indexed: false },
      { name: "claimDeadline", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RoundTerminal",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "state", type: "uint8", indexed: true },
      { name: "funderRefund", type: "uint256", indexed: false },
      { name: "compensation", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "commitKey", type: "bytes32", indexed: true },
      { name: "payoutAddress", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CreditAccrued",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CreditWithdrawn",
    inputs: [
      { name: "recipient", type: "address", indexed: true },
      { name: "destination", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "StaleSharesReturned",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "funder", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "getRound",
    stateMutability: "view",
    inputs: [{ name: "roundId", type: "uint256" }],
    outputs: [{ name: "round", type: "tuple", components: roundComponents }],
  },
  {
    type: "function",
    name: "getCommit",
    stateMutability: "view",
    inputs: [{ name: "commitKey", type: "bytes32" }],
    outputs: [{ name: "record", type: "tuple", components: commitComponents }],
  },
  {
    type: "function",
    name: "roundRevealKey",
    stateMutability: "view",
    inputs: [
      { name: "roundId", type: "uint256" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "commitKey", type: "bytes32" }],
  },
  {
    type: "function",
    name: "withdrawableCredit",
    stateMutability: "view",
    inputs: [{ name: "recipient", type: "address" }],
    outputs: [{ name: "amount", type: "uint256" }],
  },
] as const satisfies Abi;

export const credentialIssuerAbi = [
  {
    type: "event",
    name: "SignerRotated",
    inputs: [
      { name: "previousEpoch", type: "uint64", indexed: true },
      { name: "newEpoch", type: "uint64", indexed: true },
      { name: "newSigner", type: "address", indexed: true },
      { name: "emergency", type: "bool", indexed: false },
      { name: "previousEpochAcceptedUntil", type: "uint64", indexed: false },
    ],
  },
] as const satisfies Abi;

export const tokenlessFeedbackBonusAbi = [
  {
    type: "event",
    name: "PoolCreated",
    inputs: [
      { name: "poolId", type: "uint256", indexed: true },
      { name: "reviewId", type: "bytes32", indexed: true },
      { name: "contentId", type: "bytes32", indexed: true },
      { name: "admissionPolicyHash", type: "bytes32", indexed: false },
      { name: "payer", type: "address", indexed: false },
      { name: "funder", type: "address", indexed: false },
      { name: "awarder", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "feedbackDeadline", type: "uint64", indexed: false },
      { name: "awardDeadline", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FeedbackRegistered",
    inputs: [
      { name: "poolId", type: "uint256", indexed: true },
      { name: "feedbackKey", type: "bytes32", indexed: true },
      { name: "responseHash", type: "bytes32", indexed: true },
      { name: "voteKey", type: "address", indexed: false },
      { name: "payoutCommitment", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FeedbackAwarded",
    inputs: [
      { name: "poolId", type: "uint256", indexed: true },
      { name: "feedbackKey", type: "bytes32", indexed: true },
      { name: "responseHash", type: "bytes32", indexed: true },
      { name: "voteKey", type: "address", indexed: false },
      { name: "payoutCommitment", type: "bytes32", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FeedbackAwardClaimed",
    inputs: [
      { name: "poolId", type: "uint256", indexed: true },
      { name: "feedbackKey", type: "bytes32", indexed: true },
      { name: "payoutAddress", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RemainderRefunded",
    inputs: [
      { name: "poolId", type: "uint256", indexed: true },
      { name: "funder", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const satisfies Abi;
