import type { Locale } from "~~/i18n/config";

const copy = {
  en: {
    title: "Reference panel",
    subtitle: "Freeze the review standard and prepare selected cases for named review.",
    loading: "Loading reference-panel work…",
    loadError: "Reference-panel work could not be loaded.",
    empty: "No reference-panel work is assigned to this account.",
    project: "Project and reporting window",
    reportingWindow: "Reporting window",
    rulesTitle: "Fixed decision rules",
    matches: "Matches the policy → Fail",
    doesNotMatch: "Does not match the policy → Pass",
    uncertainty:
      "Reviewers choose only those two outcomes. An adjudicator may choose Uncertain only when reviewers disagree.",
    adjudication: "A qualified person who did not sit on the panel resolves disagreements.",
    definitionTitle: "Frozen definition",
    definitionMissing: "The assigned auditor must freeze the definition before units can be registered.",
    version: "Definition version",
    standardId: "Standard ID",
    standardVersion: "Standard version",
    standardHash: "Standard file hash",
    question: "Review question",
    freeze: "Freeze reference definition",
    freezing: "Freezing…",
    freezeConsequence: "This definition cannot be changed after it is frozen.",
    frozen: "Definition frozen.",
    sourceReadiness: "Source readiness",
    selected: "Selected",
    ready: "Source-ready",
    registered: "Registered",
    registerTitle: "Register a selected unit",
    selectedUnit: "Selected case",
    preparedRun: "Frozen named-review run",
    qualification: "Required language level",
    reviewers: "Reviewers",
    chooseUnit: "Choose a source-ready case",
    chooseRun: "Choose a frozen run",
    register: "Register unit",
    registering: "Registering…",
    unitRegistered: "Unit registered.",
    registeredStatus: "Registered-unit status",
    assigned: "Assigned",
    responses: "Responses",
    materializationRetrying: "Response processing needs another attempt.",
    materializationCooldown: "Response processing can be retried after",
    materializationFailureCount: "Failed attempts",
    retryResponseProcessing: "Retry response processing",
    retryingResponseProcessing: "Retrying response processing…",
    responseProcessingRetried: "Response processing retried.",
    terminal: "Terminal",
    waiting: "Waiting for complete reviewer coverage.",
    disagreement: "Waiting for a qualified adjudicator.",
    adjudicatorAssignmentPending: "Assign one qualified non-panel adjudicator for this disagreement.",
    adjudicatorPrincipal: "Adjudicator principal",
    assignAdjudicator: "Assign adjudicator",
    assigningAdjudicator: "Assigning…",
    adjudicatorAssigned: "Adjudicator assigned.",
    freezeOutcome: "Freeze outcome",
    freezingOutcome: "Freezing outcome…",
    outcomeFrozen: "Outcome frozen.",
    declareGap: "Declare nonresponse gap",
    declareAdjudicatorGap: "Close after adjudicator nonresponse",
    declaringGap: "Declaring gap…",
    gapDeclared: "Nonresponse gap declared.",
    gapPending: "A gap can be declared only after the exact reviewer deadline with incomplete coverage.",
    selfIdentificationReported: "Authenticated content self-identification reports:",
    confirmSelfIdentificationGap: "Confirm self-identification gap",
    selfIdentificationGapDeclared: "Content self-identification gap confirmed.",
    labelSet: "Reference label set",
    freezeLabelSet: "Freeze label set",
    freezingLabelSet: "Freezing label set…",
    labelSetFrozen: "Label set frozen.",
    labelSetPending: "Every selected unit must have a terminal outcome first.",
    adjudicationTitle: "Disagreements to adjudicate",
    adjudicationTask: "Unresolved policy disagreement",
    openArtifact: "Open exact artifact",
    openingArtifact: "Opening artifact…",
    artifact: "Exact blinded artifact",
    artifactRequired: "Open and load the exact artifact before deciding.",
    adjudicationOutcome: "Adjudicated outcome",
    pass: "Pass",
    fail: "Fail",
    uncertain: "Uncertain",
    noConflict: "I confirm that I have no conflict with this case or its panel.",
    rationale: "Adjudication rationale",
    rationaleHint: "At least 20 characters.",
    adjudicate: "Record adjudication",
    adjudicating: "Recording…",
    adjudicated: "Adjudication recorded.",
    noReadyUnits: "No unregistered source-ready cases are available.",
    noPreparedRuns: "No unused frozen customer-named run is ready.",
    noCompatibleRuns: "No frozen run matches this case's authoritative artifact.",
    requestFailed: "The action could not be completed.",
  },
  de: {
    title: "Referenzpanel",
    subtitle: "Prüfstandard festlegen und ausgewählte Fälle für die benannte Prüfung vorbereiten.",
    loading: "Referenzpanel-Aufgaben werden geladen…",
    loadError: "Referenzpanel-Aufgaben konnten nicht geladen werden.",
    empty: "Diesem Konto sind keine Referenzpanel-Aufgaben zugewiesen.",
    project: "Projekt und Berichtszeitraum",
    reportingWindow: "Berichtszeitraum",
    rulesTitle: "Feste Entscheidungsregeln",
    matches: "Entspricht der Richtlinie → Nicht bestanden",
    doesNotMatch: "Entspricht der Richtlinie nicht → Bestanden",
    uncertainty:
      "Prüfende wählen nur diese beiden Ergebnisse. Nur bei Uneinigkeit darf die Schlichtung „Unklar“ festlegen.",
    adjudication: "Eine qualifizierte Person, die nicht am Panel teilgenommen hat, entscheidet bei Uneinigkeit.",
    definitionTitle: "Festgelegte Definition",
    definitionMissing:
      "Die zugewiesene Prüfungsperson muss die Definition festlegen, bevor Einheiten registriert werden.",
    version: "Definitionsversion",
    standardId: "Standard-ID",
    standardVersion: "Standardversion",
    standardHash: "Hash der Standarddatei",
    question: "Prüffrage",
    freeze: "Referenzdefinition festlegen",
    freezing: "Wird festgelegt…",
    freezeConsequence: "Diese Definition kann danach nicht geändert werden.",
    frozen: "Definition festgelegt.",
    sourceReadiness: "Quellenbereitschaft",
    selected: "Ausgewählt",
    ready: "Quellenbereit",
    registered: "Registriert",
    registerTitle: "Ausgewählte Einheit registrieren",
    selectedUnit: "Ausgewählter Fall",
    preparedRun: "Festgelegter benannter Prüflauf",
    qualification: "Erforderliches Sprachniveau",
    reviewers: "Prüfende",
    chooseUnit: "Quellenbereiten Fall auswählen",
    chooseRun: "Festgelegten Lauf auswählen",
    register: "Einheit registrieren",
    registering: "Wird registriert…",
    unitRegistered: "Einheit registriert.",
    registeredStatus: "Status registrierter Einheiten",
    assigned: "Zugewiesen",
    responses: "Antworten",
    materializationRetrying: "Die Antwortverarbeitung benötigt einen weiteren Versuch.",
    materializationCooldown: "Die Antwortverarbeitung kann erneut versucht werden nach",
    materializationFailureCount: "Fehlgeschlagene Versuche",
    retryResponseProcessing: "Antwortverarbeitung erneut versuchen",
    retryingResponseProcessing: "Antwortverarbeitung wird erneut versucht…",
    responseProcessingRetried: "Antwortverarbeitung wurde erneut versucht.",
    terminal: "Abgeschlossen",
    waiting: "Warten auf vollständige Antworten des Panels.",
    disagreement: "Warten auf eine qualifizierte Schlichtung.",
    adjudicatorAssignmentPending: "Eine qualifizierte Person außerhalb des Panels für diese Uneinigkeit zuweisen.",
    adjudicatorPrincipal: "Schlichtungs-Prinzipal",
    assignAdjudicator: "Schlichtung zuweisen",
    assigningAdjudicator: "Wird zugewiesen…",
    adjudicatorAssigned: "Schlichtung zugewiesen.",
    freezeOutcome: "Ergebnis festlegen",
    freezingOutcome: "Ergebnis wird festgelegt…",
    outcomeFrozen: "Ergebnis festgelegt.",
    declareGap: "Lücke wegen Nichtantwort erklären",
    declareAdjudicatorGap: "Nach Nichtantwort der Schlichtung abschließen",
    declaringGap: "Lücke wird erklärt…",
    gapDeclared: "Lücke wegen Nichtantwort erklärt.",
    gapPending: "Eine Lücke ist erst nach der genauen Frist bei unvollständigen Antworten möglich.",
    selfIdentificationReported: "Authentifizierte Meldungen zur Selbstidentifikation im Inhalt:",
    confirmSelfIdentificationGap: "Lücke durch Selbstidentifikation bestätigen",
    selfIdentificationGapDeclared: "Lücke durch Selbstidentifikation im Inhalt bestätigt.",
    labelSet: "Referenz-Labelsatz",
    freezeLabelSet: "Labelsatz festlegen",
    freezingLabelSet: "Labelsatz wird festgelegt…",
    labelSetFrozen: "Labelsatz festgelegt.",
    labelSetPending: "Zuerst braucht jede ausgewählte Einheit ein endgültiges Ergebnis.",
    adjudicationTitle: "Zu schlichtende Uneinigkeiten",
    adjudicationTask: "Ungelöste Uneinigkeit zur Richtlinie",
    openArtifact: "Genaues Artefakt öffnen",
    openingArtifact: "Artefakt wird geöffnet…",
    artifact: "Genaues verblindetes Artefakt",
    artifactRequired: "Vor der Entscheidung muss das genaue Artefakt geöffnet und geladen werden.",
    adjudicationOutcome: "Ergebnis der Schlichtung",
    pass: "Bestanden",
    fail: "Nicht bestanden",
    uncertain: "Unklar",
    noConflict: "Ich bestätige, dass kein Konflikt mit diesem Fall oder seinem Panel besteht.",
    rationale: "Begründung der Schlichtung",
    rationaleHint: "Mindestens 20 Zeichen.",
    adjudicate: "Schlichtung speichern",
    adjudicating: "Wird gespeichert…",
    adjudicated: "Schlichtung gespeichert.",
    noReadyUnits: "Keine unregistrierten quellenbereiten Fälle verfügbar.",
    noPreparedRuns: "Kein ungenutzter festgelegter Lauf mit benannten Prüfenden ist bereit.",
    noCompatibleRuns: "Kein festgelegter Lauf stimmt mit dem maßgeblichen Artefakt dieses Falls überein.",
    requestFailed: "Die Aktion konnte nicht abgeschlossen werden.",
  },
} as const;

export function dsaReferencePanelCopy(locale: Locale) {
  return copy[locale];
}
