import { derivePaidLaneActivationReference } from "~~/lib/tokenless/paidLaneActivation";

const NAMES = [
  "TOKENLESS_PAID_LANES_DPIA_APPROVAL_REFERENCE",
  "TOKENLESS_PAID_LANES_TRANSFER_INVENTORY_APPROVAL_REFERENCE",
  "TOKENLESS_PAID_LANES_FUNDING_VALIDATION_REFERENCE",
  "TOKENLESS_INVITED_PAID_ADULTHOOD_APPROVAL_REFERENCE",
  "TOKENLESS_PAID_LANES_COMPLIANCE_APPROVED_AT",
  "TOKENLESS_PRIVATE_PAID_REVIEWS_ENABLED",
  "NEXT_PUBLIC_TOKENLESS_PRIVATE_PAID_REVIEWS_ENABLED",
  "TOKENLESS_NETWORK_PANELS_ENABLED",
  "NEXT_PUBLIC_TOKENLESS_NETWORK_PANELS_ENABLED",
  "TOKENLESS_HYBRID_REVIEWS_ENABLED",
  "NEXT_PUBLIC_TOKENLESS_HYBRID_REVIEWS_ENABLED",
  "WORLD_ID_APP_ID",
  "WORLD_ID_RP_ID",
  "WORLD_ID_ENVIRONMENT",
  "NEXT_PUBLIC_TOKENLESS_PAID_LANES_ACTIVATION_REFERENCE",
] as const;

export function configurePaidLaneTestEnvironment() {
  const previous = Object.fromEntries(NAMES.map(name => [name, process.env[name]]));
  Object.assign(process.env, {
    TOKENLESS_PAID_LANES_DPIA_APPROVAL_REFERENCE: `sha256:${"a".repeat(64)}`,
    TOKENLESS_PAID_LANES_TRANSFER_INVENTORY_APPROVAL_REFERENCE: `sha256:${"b".repeat(64)}`,
    TOKENLESS_PAID_LANES_FUNDING_VALIDATION_REFERENCE: `sha256:${"c".repeat(64)}`,
    TOKENLESS_INVITED_PAID_ADULTHOOD_APPROVAL_REFERENCE: `sha256:${"d".repeat(64)}`,
    TOKENLESS_PAID_LANES_COMPLIANCE_APPROVED_AT: "2026-07-20T12:00:00.000Z",
    TOKENLESS_PRIVATE_PAID_REVIEWS_ENABLED: "true",
    NEXT_PUBLIC_TOKENLESS_PRIVATE_PAID_REVIEWS_ENABLED: "true",
    TOKENLESS_NETWORK_PANELS_ENABLED: "true",
    NEXT_PUBLIC_TOKENLESS_NETWORK_PANELS_ENABLED: "true",
    TOKENLESS_HYBRID_REVIEWS_ENABLED: "false",
    NEXT_PUBLIC_TOKENLESS_HYBRID_REVIEWS_ENABLED: "false",
    WORLD_ID_APP_ID: "app_testfixture",
    WORLD_ID_RP_ID: "rp_testfixture",
    WORLD_ID_ENVIRONMENT: "production",
  });
  process.env.NEXT_PUBLIC_TOKENLESS_PAID_LANES_ACTIVATION_REFERENCE = derivePaidLaneActivationReference(process.env);
  return () => {
    for (const name of NAMES) {
      const value = previous[name];
      if (value === undefined) delete process.env[name];
      else process.env[name] = value;
    }
  };
}
