import { index, onchainTable } from "ponder";

export const tokenlessRound = onchainTable(
  "tokenless_round",
  (t) => ({
    id: t.text().primaryKey(),
    deploymentKey: t.text().notNull(),
    roundId: t.bigint().notNull(),
    funder: t.hex().notNull(),
    contentId: t.hex().notNull(),
    termsHash: t.hex().notNull(),
    beaconNetworkHash: t.hex().notNull(),
    beaconRound: t.bigint().notNull(),
    feeRecipient: t.hex().notNull(),
    bountyAmount: t.bigint().notNull(),
    feeAmount: t.bigint().notNull(),
    attemptReserve: t.bigint().notNull(),
    attemptCompensation: t.bigint().notNull(),
    compensationPerRecipient: t.bigint().notNull().default(0n),
    funderRefund: t.bigint().notNull().default(0n),
    totalCompensation: t.bigint().notNull().default(0n),
    totalAccuracyScore: t.bigint().notNull().default(0n),
    totalPaid: t.bigint().notNull().default(0n),
    minimumReveals: t.integer().notNull(),
    maximumCommits: t.integer().notNull(),
    admissionPolicyHash: t.hex().notNull(),
    commitCount: t.integer().notNull().default(0),
    revealCount: t.integer().notNull().default(0),
    frozenRevealCount: t.integer().notNull().default(0),
    aggregateCursor: t.integer().notNull().default(0),
    weightCursor: t.integer().notNull().default(0),
    upVotes: t.integer().notNull().default(0),
    state: t.integer().notNull().default(0),
    commitDeadline: t.bigint().notNull(),
    revealDeadline: t.bigint().notNull(),
    beaconFailureDeadline: t.bigint().notNull(),
    claimGracePeriod: t.bigint().notNull(),
    claimDeadline: t.bigint().notNull().default(0n),
    staleReturned: t.boolean().notNull().default(false),
    staleAmount: t.bigint().notNull().default(0n),
    createdAt: t.bigint().notNull(),
    createdBlock: t.bigint().notNull(),
    createdTxHash: t.hex().notNull(),
    updatedAt: t.bigint().notNull(),
  }),
  (table) => ({
    deploymentRoundIdx: index().on(table.deploymentKey, table.roundId),
    stateDeadlineIdx: index().on(table.state, table.revealDeadline),
    funderIdx: index().on(table.funder),
    contentIdx: index().on(table.contentId),
    admissionPolicyIdx: index().on(table.deploymentKey, table.admissionPolicyHash),
  }),
);

export const tokenlessCommit = onchainTable(
  "tokenless_commit",
  (t) => ({
    id: t.text().primaryKey(),
    deploymentKey: t.text().notNull(),
    commitKey: t.hex().notNull(),
    roundId: t.bigint().notNull(),
    voteKey: t.hex().notNull(),
    nullifier: t.hex().notNull(),
    sealedCommitment: t.hex().notNull(),
    sealedPayloadHash: t.hex().notNull(),
    sealedPayload: t.hex().notNull(),
    payoutCommitment: t.hex().notNull(),
    responseHash: t.hex().notNull(),
    vote: t.integer().notNull().default(0),
    predictedUpBps: t.integer().notNull().default(0),
    accuracyScore: t.bigint().notNull().default(0n),
    revealed: t.boolean().notNull().default(false),
    claimed: t.boolean().notNull().default(false),
    committedAt: t.bigint().notNull(),
    revealedAt: t.bigint(),
    commitTxHash: t.hex().notNull(),
    commitLogIndex: t.integer().notNull(),
  }),
  (table) => ({
    deploymentCommitIdx: index().on(table.deploymentKey, table.commitKey),
    roundIdx: index().on(table.roundId),
    nullifierIdx: index().on(table.nullifier),
    voteKeyIdx: index().on(table.voteKey),
  }),
);

export const tokenlessClaim = onchainTable(
  "tokenless_claim",
  (t) => ({
    id: t.text().primaryKey(),
    deploymentKey: t.text().notNull(),
    roundId: t.bigint().notNull(),
    commitKey: t.hex().notNull(),
    payoutAddress: t.hex().notNull(),
    amount: t.bigint().notNull(),
    claimedAt: t.bigint().notNull(),
    txHash: t.hex().notNull(),
    logIndex: t.integer().notNull(),
  }),
  (table) => ({
    roundIdx: index().on(table.roundId),
    payoutIdx: index().on(table.payoutAddress),
  }),
);

export const tokenlessCreditBalance = onchainTable(
  "tokenless_credit_balance",
  (t) => ({
    id: t.text().primaryKey(),
    deploymentKey: t.text().notNull(),
    owner: t.hex().notNull(),
    remainingCredit: t.bigint().notNull(),
    totalAccrued: t.bigint().notNull(),
    totalWithdrawn: t.bigint().notNull(),
    updatedAt: t.bigint().notNull(),
    updatedBlock: t.bigint().notNull(),
  }),
  (table) => ({
    deploymentOwnerIdx: index().on(table.deploymentKey, table.owner),
  }),
);

export const tokenlessCreditEvent = onchainTable(
  "tokenless_credit_event",
  (t) => ({
    id: t.text().primaryKey(),
    deploymentKey: t.text().notNull(),
    owner: t.hex().notNull(),
    eventType: t.text().notNull(),
    roundId: t.bigint(),
    destination: t.hex(),
    amount: t.bigint().notNull(),
    remainingCredit: t.bigint().notNull(),
    occurredAt: t.bigint().notNull(),
    blockNumber: t.bigint().notNull(),
    txHash: t.hex().notNull(),
    logIndex: t.integer().notNull(),
  }),
  (table) => ({
    deploymentOwnerIdx: index().on(table.deploymentKey, table.owner),
    deploymentRoundIdx: index().on(table.deploymentKey, table.roundId),
  }),
);

export const tokenlessIssuerEpoch = onchainTable(
  "tokenless_issuer_epoch",
  (t) => ({
    id: t.text().primaryKey(),
    deploymentKey: t.text().notNull(),
    previousEpoch: t.bigint().notNull(),
    epoch: t.bigint().notNull(),
    signer: t.hex().notNull(),
    emergency: t.boolean().notNull(),
    previousEpochAcceptedUntil: t.bigint().notNull(),
    rotatedAt: t.bigint().notNull(),
    txHash: t.hex().notNull(),
  }),
  (table) => ({
    deploymentEpochIdx: index().on(table.deploymentKey, table.epoch),
    signerIdx: index().on(table.signer),
  }),
);
