[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/ponder/Dockerfile"
watchPatterns = [
  ".yarn/**",
  ".yarnrc.yml",
  "package.json",
  "yarn.lock",
  "packages/ponder/**",
]

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 120
