// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface ILaunchDistributionPool {
    struct LaunchRewardPolicy {
        uint16 minQualifyingScoreBps;
        uint16 minVoters;
        uint16 minVerifiedHumans;
        uint16 minDistinctVerifiedAnchors;
        uint16 minDistinctAnchorRounds;
        uint64 minLaunchCreditStake;
        uint16 maxDistinctRatersPerVerifiedAnchor;
        uint16 maxUnverifiedCreditsPerRound;
        uint16 unverifiedEarnedRaterCapBps;
        uint32 minAnchorCredentialAgeSeconds;
        uint32 eligibilityRatingCount;
        uint32 rewardingRatingCount;
        bool requireNoPendingCleanup;
    }

    function launchAnchorCredentialAgeSeconds() external view returns (uint32);
    function raterRoundCreditRecorded(address rater, uint256 contentId, uint256 roundId) external view returns (bool);

    /// @notice Autogenerated getter for the per-commit recorded flag. Used by
    ///         `RoundRewardDistributor._tryRecordLaunchRaterCredit` to verify the launch pool
    ///         actually advanced its state on a non-reverting `recordEarnedRaterReward*` call
    ///         (M-Retry-1 from audit-claude-2026-05-20).
    function earnedRewardCreditRecorded(uint256 contentId, uint256 roundId, bytes32 commitKey)
        external
        view
        returns (bool);

    function recordEarnedRaterRewardWithSourceReady(
        address rater,
        uint256 contentId,
        uint256 roundId,
        bytes32 commitKey,
        uint16 scoreBps,
        uint16 revealedRaterCount,
        bool noPendingCleanup,
        uint256 stakeAmount,
        bytes32[] calldata verifiedAnchorIds,
        uint64 sourceReadyAt
    ) external returns (uint256 paidAmount);

    function recordAdvisoryRaterRewardWithSourceReady(
        address rater,
        uint256 contentId,
        uint256 roundId,
        bytes32 advisoryCommitKey,
        uint16 scoreBps,
        uint16 revealedRaterCount,
        bool noPendingCleanup,
        bytes32[] calldata verifiedAnchorIds,
        uint64 sourceReadyAt
    ) external returns (bool recorded, uint256 paidAmount);
}
