// SPDX-License-Identifier: MIT
pragma solidity ^0.8.34;

import { RaterRegistry } from "../RaterRegistry.sol";
import { IClusterPayoutOracle } from "./IClusterPayoutOracle.sol";

interface IRevealGraceConfig {
    function revealGracePeriod() external view returns (uint256);
}

interface IRoundClusterReadyAtSource {
    function roundLifecycleState(uint256 contentId, uint256 roundId)
        external
        view
        returns (
            uint256 revealGracePeriod,
            uint256 lastRevealableAfter,
            uint256 cleanupRemaining,
            uint48 clusterPayoutReadyAt
        );
    function roundCore(uint256 contentId, uint256 roundId)
        external
        view
        returns (
            uint48 startTime,
            uint8 state,
            uint16 voteCount,
            uint16 revealedCount,
            uint64 totalStake,
            uint48 thresholdReachedAt,
            uint48 settledAt
        );
    function protocolConfig() external view returns (IRevealGraceConfig);
}

interface ILaunchDistributionPool {
    struct LaunchRewardPolicy {
        uint16 minQualifyingScoreBps;
        uint16 minVoters;
        uint16 minVerifiedHumans;
        uint16 minDistinctVerifiedAnchors;
        uint16 minDistinctAnchorRounds;
        uint64 minLaunchCreditStake;
        uint16 maxDistinctRatersPerVerifiedAnchor;
        uint16 maxUnverifiedCreditsPerRound;
        uint16 unverifiedEarnedRaterCapBps;
        uint32 minAnchorCredentialAgeSeconds;
        uint32 eligibilityRatingCount;
        uint32 rewardingRatingCount;
        bool requireNoPendingCleanup;
    }

    function launchAnchorCredentialAgeSeconds() external view returns (uint32);
    function clusterPayoutOracle() external view returns (IClusterPayoutOracle);
    function launchRewardPolicy()
        external
        view
        returns (
            uint16 minQualifyingScoreBps,
            uint16 minVoters,
            uint16 minVerifiedHumans,
            uint16 minDistinctVerifiedAnchors,
            uint16 minDistinctAnchorRounds,
            uint64 minLaunchCreditStake,
            uint16 maxDistinctRatersPerVerifiedAnchor,
            uint16 maxUnverifiedCreditsPerRound,
            uint16 unverifiedEarnedRaterCapBps,
            uint32 minAnchorCredentialAgeSeconds,
            uint32 eligibilityRatingCount,
            uint32 rewardingRatingCount,
            bool requireNoPendingCleanup
        );
    function raterRegistry() external view returns (RaterRegistry);
    function roundClusterReadyAtSource() external view returns (IRoundClusterReadyAtSource);
    function raterRoundCreditRecorded(address rater, uint256 contentId, uint256 roundId) external view returns (bool);
    function roundUnverifiedLaunchCreditCount(uint256 contentId, uint256 roundId) external view returns (uint16);
    function authorizedCallers(address caller) external view returns (bool);

    function claimLegacyContributorAllocation(uint256 allocation, bytes32[] calldata proof)
        external
        returns (uint256 paidAmount);

    function claimLegacyContributorAllocationTo(address recipient, uint256 allocation, bytes32[] calldata proof)
        external
        returns (uint256 paidAmount);

    function claimableLegacyContributorAllocation(address account, uint256 allocation, bytes32[] calldata proof)
        external
        view
        returns (uint256);

    function vestedLegacyContributorAllocation(address account, uint256 allocation, bytes32[] calldata proof)
        external
        view
        returns (uint256);

    function sweepExpiredLegacyContributorAllocationToTreasury() external returns (uint256 sweptAmount);

    /// @notice Autogenerated getter for the per-commit recorded flag. Used by
    ///         `RoundRewardDistributor._tryRecordLaunchRaterCredit` to verify the launch pool
    ///         actually advanced its state on a non-reverting `recordEarnedRaterReward*` call
    ///         (M-Retry-1 from audit-claude-2026-05-20).
    function earnedRewardCreditRecorded(uint256 contentId, uint256 roundId, bytes32 commitKey)
        external
        view
        returns (bool);

    function recordEarnedRaterRewardWithSourceReady(
        address rater,
        uint256 contentId,
        uint256 roundId,
        bytes32 commitKey,
        uint16 scoreBps,
        uint16 revealedRaterCount,
        bool noPendingCleanup,
        uint256 stakeAmount,
        bytes32[] calldata verifiedAnchorIds,
        uint64 sourceReadyAt
    ) external returns (uint256 paidAmount);

    function recordAdvisoryRaterRewardWithSourceReady(
        address rater,
        uint256 contentId,
        uint256 roundId,
        bytes32 advisoryCommitKey,
        uint16 scoreBps,
        uint16 revealedRaterCount,
        bool noPendingCleanup,
        bytes32[] calldata verifiedAnchorIds,
        uint64 sourceReadyAt
    ) external returns (bool recorded, uint256 paidAmount);
}
